title: Java to Kotlin
subtitle: A Refactoring Guidebook
logo: book-cover-small.jpeg
description: Supplementary resources
show_downloads: false
github:
  is_user_page: false
exclude:
  - .*
  - CNAME
  - Dockerfile
  - Gemfile
  - README.md
  - .gitignore
  - site-*
  - code-examples
  - lib
  - gradle
  - gradle.properties
  - gradlew
  - build.gradle
  - settings.gradle
  - buildSrc
  - build
plugins:
  - jekyll-feed
  - jekyll-sitemap
asciidoc: {}
asciidoctor: {}
collections:
  route_changes:
    output: true
    layout: default
  journeys:
    output: true
    layout: default
