theme: jekyll-theme-minimal
title: Java to Kotlin
subtitle: A Refactoring Guidebook
logo: book-cover-small.jpeg
description: Supplementary resources
show_downloads: false
github:
  is_user_page: false
exclude:
  - .*
  - CNAME
  - Dockerfile
  - Gemfile
  - README.md
  - .gitignore
  - site-*
plugins:
  - jekyll-asciidoc
  - jekyll-feed
  - jekyll-sitemap
